version: '3.8'
services:
  app:
    build: .
    container_name: mypage
    ports:
      - '8080:8080' # ホストOSのポート番号：コンテナのポート番号
    volumes:
      - type: bind
        source: "./src" # ホストOS上のディレクトリ
        target: "/mypage/src" # コンテナ上でマウントするディレクトリ
    stdin_open: true
    tty: true